### ISSUE TITLE
Editing Help

### ISSUE THREAD

**Issue by Owlz** [angr/simuvex#10]
Hey,

So I'm trying to add a simuvex call for fclose. The basics are simple, but I'm also suggesting changing the posix.py module to include a "fd_closed" list that will be used to track when fds get closed. The obvious problem with the way files appear to be handled now is that they're simply removed, so "closing" a file isn't really what one would want from a simulation.

I've done most of the work for an initial handling of it in this way, however the fd_closed list that I create in posix __init__ doesn't appear to get passed on through execution. I've tried adding the following:

        self.fd_closed = [] if fd_closed is None else fd_closed

and adding fd_close=None in the init, but that doesn't propagate it. Help?

**Comment by Owlz** [comment]
Actually, looking at the latest commits (6 days ago) @zardus seems to have changed the same code that I was looking at.

**Comment by zardus** [comment]
Sorry about that :-).

I ended up putting a "closed" attribute on the SimFile object itself. The
downside is that currently, closed files aren't cleared out, so you don't
end up reusing file descriptors. We should definitely save them off
somewhere, instead.

To propagate your list in the plugin, you'd need to add code to do that to
the `copy()` method of the posix plugin. That's what's called when paths
split.
