### ISSUE TITLE
can i use simuvex to simplify the statements sets  generated from  pyvex

### ISSUE THREAD

**Issue by yangshouguo** [angr/simuvex#105]
can i use simuvex to simplify the statements sets  generated from  pyvex .
problem : when i use pyvex , i got some statemens like ( a = 1 , b = a  ) , i wanna simplify them and get b = 1 . how can i do it ?

**Comment by zardus** [comment]
You can use `state.se.simplify()` to simplify the state constraints. It should be able to reduce trivial cases like that.

**Comment by yangshouguo** [comment]
can you give a simple case to simplify the statements from pyvex? 
i am a fresh programer. I can't figure out how          To use state.se.simplify.

发自我的 iPhone

**Comment by zardus** [comment]
There are two ways:

1. Add the `simuvex.options.OPTIMIZE_IR` option to the state with `state.options.add(simuvex.options.OPTIMIZE_IR)`, then when that state is stepped forward, angr will have VEX optimize the IR.
2. After stepping your path forward, use `path.state.se.simplify()`, after which `path.state.se.constraints` will be the simplified constraints that you're looking for.

The two work on different levels, and it's probably best to use both.

**Comment by rhelmot** [comment]
this was resolved via email
