### ISSUE TITLE
Error in initial_state.mem

### ISSUE THREAD

**Issue by ikhwan12** [angr/simuvex#148]
Hello !
I have a problem to solve this error:
![image](https://user-images.githubusercontent.com/16043445/28348677-d4c145d6-6c70-11e7-8485-7788f7eef2ad.png)

Based on the error message, I should check my code line in here:

    # Create a blank state at the start of check function
	initial_state = proj.factory.blank_state(addr=0x804846D, remove_options={simuvex.o.LAZY_SOLVES})

	# The flag is a bit vector containing 30 bytes, each byte contains 8 bits
	initial_state.mem[0x804B060] = initial_state.se.BVS('flag', 30*8)

	# Setup return address
	initial_state.mem[initial_state.regs.esp].dword = 0x8049A49

I still practice to use angr. I am so happy if there is someone who want to help me to solve this error.
Thank you.

**Comment by rhelmot** [comment]
Hi! If you're trying to store raw, untyped data, i.e. your flag bitvector, you don't want to use `state.mem`, you want to use `state.memory`. In this case, you should replace your second statement with `initial_state.memory.store(0x804b060, initial_state.se.BVS('flag', 30*8)`.

**Comment by ikhwan12** [comment]
Oh my God, It works, man!
Thank you so much. I really appreciate it.

**Comment by rhelmot** [comment]
No problem :)
