### ISSUE TITLE
fgets posix newline missing

### ISSUE THREAD

**Issue by Owlz** [angr/simuvex#24]
Playing with this test binary, i discovered that the fgets call appears to not be saving the newline entered from stdin.

[login.zip](https://github.com/angr/simuvex/files/285487/login.zip)

I finds the correct values and appears to populate memory correctly, but it forgets to add the newline character to the posix input file, so replaying the input doesn't correctly generate the path. My guess is similar problems may exist with other generic input sim functions, but not 100% sure.

Re-creating should be as simple as path group exploring the binary to successful print, then state.posix.dumps(0).

**Comment by zardus** [comment]
Thanks for finding that! Do you have a fix you could PR, by any chance?

**Comment by Owlz** [comment]
Just looked at this again. At some point, looks like this was fixed. Probably fine to close this IMO.
