### ISSUE TITLE
sscanf issue with crackme?

### ISSUE THREAD

**Issue by Owlz** [angr/simuvex#25]
Folks,

I'm wondering if i stumbled on to another sscanf issue. I'm playing around with the crackme challenges (https://github.com/radare/radare2book/blob/master/crackmes/ioli/IOLI-crackme.tar.gz). Specifically, crackme0x04. When loading it up and exploring using:

```python
pg.explore(find=0x80484E8)
pg.found[0].state.posix.dumps(0)
```

It appears to find a segfault in the program (likely not intended on their part). However, it will find paths through to the successful login that, when played into the program, don't actually get to that part of the program.

**Comment by zardus** [comment]
My guess is that this is a similar issue to https://github.com/angr/angr/issues/128

From discussion on IRC, basically, our scanf simprocedure really sucks. We've improved it a bit, but there's no way that a performant *and* faithful summary of something like scanf (which is [turing complete](https://github.com/HexHive/printbf)).

I added an entry to the "angr gotchas" (http://docs.angr.io/docs/gotchas.html) that discusses possible workarounds.

**Comment by Manouchehri** [comment]
@zardus Is there a way to get angr to *not* silently fail?

**Comment by zardus** [comment]
Yep, check out http://docs.angr.io/docs/gotchas.html

You can eliminate most of the subtle execution differences by disabling
SimProcedures, but that has drawbacks as discussed in those docs. In the
end, though, angr's symbolic execution component is basically a symbolic
emulator. Any emulator is going to have inaccuracies; we just have to track
them down and fix them.

**Comment by Manouchehri** [comment]
Probably fixed now? https://github.com/angr/angr/issues/128#issuecomment-239591534

**Comment by rhelmot** [comment]
Definitely fixed, considering it's the exact same binary.
