### ISSUE TITLE
RCL (x64) can't be emulated

### ISSUE THREAD

**Issue by newgre** [angr/simuvex#47]
When trying to emulate an RCL instruction (x64) simuVEX throws an exception as the corresponding semantics aren't implemented.

**Comment by zardus** [comment]
Could you paste the exception?

**Comment by newgre** [comment]
ERROR   | 2016-12-04 19:53:12,861 | simuvex.vex.expressions.ccall | Unsupported CCall amd64g_calculate_RCL
...
raise UnsupportedCCallError("Unsupported CCall %s" % self._expr.callee.name)
simuvex.s_errors.UnsupportedCCallError: Unsupported CCall amd64g_calculate_RCL

**Comment by ltfish** [comment]
@newgre It'll be great if you can post the exact basic block that causes this, so we can write a test case based on it. Alternatively, you can also post the binary somewhere and send us the link.

**Comment by newgre** [comment]
The following script reproduces the error:

```python
import angr
import archinfo
from simuvex import SimActionData

options = {}
options["main_opts"] = {"backend": "blob", "custom_arch": "AMD64"}
b = angr.Project("test.bin", load_options=options)

print "IRSB of VM entry!"
irsb = b.factory.block(0).vex
irsb.pp()

print "[+] Simulated entry call block"
sirsb = b.factory.sim_block(b.factory.blank_state())
```

Extract attached zip file.
[rcl_error.zip](https://github.com/angr/simuvex/files/637615/rcl_error.zip)

**Comment by rhelmot** [comment]
Note for whoever gets around to this: the function you need to translate from libVEX is here https://github.com/angr/vex/blob/master/priv/guest_amd64_helpers.c#L3056

**Comment by newgre** [comment]
Same for RCR.

**Comment by rhelmot** [comment]
Luckily, in the year since this issue was opened, these instructions were implemented with x86 but not amd64. I've attempted to port them over with https://github.com/angr/angr/commit/ba4a730d000ea6affaec138b5563703051f3264d, could you check that everything works as expected?

**Comment by newgre** [comment]
```python
options = {}
options["main_opts"] = {"backend": "blob", "custom_arch": "AMD64"}
p = angr.Project("test.bin", load_options=options)
state = p.factory.blank_state()
state.step()
```
The attached file (test.bin) disassembles to:
```
rcr     ah, cl
```
and produces the following error:

> angr.errors.SimExpressionError: Inconsistent expression size: should be 64 but is 128
[test.zip](https://github.com/angr/simuvex/files/1604612/test.zip)

**Comment by rhelmot** [comment]
I fucked up that commit, there's a new one now. Try again?

**Comment by newgre** [comment]
works for me.
