### ISSUE TITLE
`SimProcedure.ret()` executes ARM version of return instruction even in Thumb mode

### ISSUE THREAD

**Issue by iamahuman** [angr/simuvex#50]
The `SimProcedure` as of now just directly interprets and executes the `ret_instruction` of the current `ArchInfo` to emulate a return from a procedure call. While this quirk may be acceptable for most situations, it may cause errors on architectures where the interpretation of instruction data depends on the current state of the processor -- one example being the AArch32 architecture where ARM and Thumb mode can coexist in a single task / context, so that the ret_instruction `bx lr` (`\x1e\xff\x2f\xe1`) would be incorrectly interpreted as `vrhadd.u16 d14, d14, d31` if the state was in the Thumb mode.

**Comment by rhelmot** [comment]
Yikes!! I have no idea how we've never run into this problem before!

Luckily, an upcoming refactor (should be done in the next week) should remove the "emulate a ret instruction" hack entirely. Will post updates!

**Comment by iamahuman** [comment]
Closing this as the refactor resolved the issue :)
