### ISSUE TITLE
atoi fails to satisfy 32-bit decimal strings with large number of digits

### ISSUE THREAD

**Issue by spyked** [angr/simuvex#57]
Hi,

I am trying to execute a small program that calls `atoi` on `argv[1]`:

```C
/* smaller_prog.c */
#include <stdio.h>

int main(int argc, char **argv)
{
	int count = atoi(argv[1]);
	printf("GOT: %d\n", count);
	return 0;
}
```
I compiled it for 32 bits:

```
$ gcc-5 -m32 smaller_prog.c -o smaller_prog
```

I am running it using the following example Angr script:

```python
#!/usr/bin/env python
import angr
import claripy
import code

# Project
b = angr.Project('./smaller_prog')

# Make arguments symbolic
arg1 = "1073741813"
#arg1 = "107374181"
st = b.factory.entry_state(args=['./smaller_prog', arg1])

# Create a path group
pg = b.factory.path_group(st)
pg.explore(find=lambda p: "GOT" in p.state.posix.dumps(1))

print pg
code.interact(local=locals())
```

The script sets `argv[1]` to a large decimal number and tries to find a path where a string containing `"GOT"` is printed. When I run the script, I get the following:

```
$ python example.py 
<PathGroup with 1 errored>
```

but if I remove one of the digits in `arg1` (e.g. if uncomment line 11 in the script), then Angr finds a path:

```
$ python example.py
<PathGroup with 1 found>
>>> pg.found[0].state.posix.dumps(1)
'GOT: 107374181\n'
```

As far as I can tell, the path in the failing run is errored because the constraints generated by `atoi` are unsatisfiable for the longer input.  I have tested with and without the `printf` and in every situation where the output of `atoi` is used, the path is either errored or unsatisfied. I've attached the output generated by `pg.errored[0].retry()` to this issue.

I am assuming that this is an implementation issue in simuvex, my apologies if it's an Angr problem (or if I'm doing something wrong).

[unsat-retry.txt](https://github.com/angr/simuvex/files/692395/unsat-retry.txt)

**Comment by salls** [comment]
angr's symbolic procedures avoid splitting the state at the cost of
requiring a max length for strings.
These limits are stored in state.libc, and you can set these to a higher
value when needed, e.g. st.libc.max_strtol_len = 11, which would make your
example work.
Higher values are currently not the default because they create large
symbolic formulas which can greatly slow down the solver.

**Comment by spyked** [comment]
The `state.libc.max_strtol_len` variable helped. Thank you for clarifying this! :)

**Comment by salls** [comment]
No problem!
