### ISSUE TITLE
unsatisfiable conditional

### ISSUE THREAD

**Issue by schieb** [angr/simuvex#66]
`x mod 1` is always 0. Perhaps you meant `addr % 4 == 2` as a quick check in case the caller forgot to specify the thumb argument (which would catch a mistake half the time). If that is the case, I think a warning would be in order. Code is [here](https://github.com/angr/simuvex/blob/bbf8488f184df6a78d1464d142e8a32664b79825/simuvex/engines/vex/engine.py#L418).
```
thumb = int(thumb)
if isinstance(arch, ArchARM):
    if addr % 1 == 1:
        thumb = 1
    if thumb:
        addr &= ~1
```

I could be completely wrong. I have zero arm experience, which is why I did not submit a PR.

**Comment by rhelmot** [comment]
Yikes, sorry about that. should have been addr % 2 == 1. Odd addresses in VEX's emulation of ARM indicate executing in thumb mode.
