### ISSUE TITLE
"SimOperationError: divide by zero!" when creating CFG of firefox in Ubuntu14.04

### ISSUE THREAD

**Issue by gitttt** [angr/simuvex#8]
My sample is: /usr/lib/firefox/firefox on a Ubuntu 14.04-3 32bit system.

I load it like this:
p = angr.Project(PATH_TO_SAMPLE, load_options={'auto_load_libs': False})

I create the control flow graph like this:
cfg = p.analyses.CFG(keep_state=False, fail_fast=True, context_sensitivity_level=0)

As output I get this:

WARNING | 2016-01-26 10:25:14,760 | simuvex.vex.irop | IROp error (for operation Iop_DivModU64to32)
Traceback (most recent call last):
  File "/home/vagrant/.environments/angr/local/lib/python2.7/site-packages/simuvex/vex/irop.py", line 822, in translate
    return operations[op].calculate( *s_args)
  File "/home/vagrant/.environments/angr/local/lib/python2.7/site-packages/simuvex/vex/irop.py", line 345, in calculate
    raise SimOperationError("divide by zero!")
SimOperationError: divide by zero!

What does it mean? Am I right to assume that it a problem of the binary (e.g. because I am not starting firefox using the appropriate script pointed to by /usr/bin/firefox?

Is it a serious problem for the CFG, i.e. does it mean the CFG is incorrect?

**Comment by zardus** [comment]
angr's CFG uses a technique called _forced execution_, which can lead to inconsistent data being thrown around. The CFG compensates for that, but some warnings escape to your screen. These are expected; sorry about the confusion :-)

**Comment by ltfish** [comment]
I should really mute those outputs by default!
