### ISSUE TITLE
AttributeError: 'IRTypeEnv' object has no attribute 'sizeof'

### ISSUE THREAD

**Issue by frapik99** [angr/simuvex#94]
Hi,
I have installed the latest simuvex from the master and I have the following error:

```
line 209, in _handle_irsb
    retval_size = state.scratch.tyenv.sizeof(stmt.tmp)
AttributeError: 'IRTypeEnv' object has no attribute 'sizeof'
```

Any idea on how to fix it?

Thanks

**Comment by rhelmot** [comment]
Please install the latest pyvex from master.

**Comment by frapik99** [comment]
Hi @rhelmot yes I was about to write again, I have done it again and it works.

Thanks
