### ISSUE TITLE
bnd retn not supported

### ISSUE THREAD

**Issue by Owlz** [angr/simuvex#98]
Making a brief detour into windows land i found errors when running the binary that related to an instruction not supported:

```python
In [7]: pg.errored[0].error
Out[7]: angr.errors.AngrExitError('IR decoding error at 0x401d24. You can hook this instruction with a python replacement using project.hook(0x401d24, your_function, length=length_of_instruction).')
```

Turns out the command was ```bnd retn```. Bytes as ```\xf2\xc3```

**Comment by ltfish** [comment]
What is `bnd retn`? I've never seen it.

**Comment by Owlz** [comment]
Yeah me neither, and I can't find any info on googles. Perhaps it's something specific w/ Microsoft VisualC 14 runtime?

Attaching the file. Angr is having problems decoding instruction at 0x401d24.
[challenge1.zip](https://github.com/angr/simuvex/files/821674/challenge1.zip)

**Comment by schieb** [comment]
Looks like it is part of a relatively new instruction set extension called MPX (Memory Protection Extensions).

See [here](https://pdfs.semanticscholar.org/bd11/4878c6471cb5ae28546a594bf25ba5c25c6f.pdf) and [here (§16.1)](https://www.cs.princeton.edu/courses/archive/fall15/cos217/reading/x86-64-1.pdf) for details.

**Comment by ltfish** [comment]
@schieb Thanks! I don't think we will support it before VEX supports it.

**Comment by rhelmot** [comment]
So it looks like that instruction set extension hijacked the REPNE prefix - F2 is usually REPNE. Apparently using REPNE RETN is identical to a typical return, except that it fixes some issues with the branch predictor on AMD CPUs.

I have implemented this in a recent commit :)
